# .streamlit/secrets.toml
DB_HOST = "localhost"
DB_USER = "root"
DB_PASSWORD = "123456"
DB_NAME = "accident_risk_db"

# Streamlit 用户配置
STREAMLIT_USER = "streamlit_user"
STREAMLIT_PASSWORD = "123456"  # 请替换为实际密码